# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='column',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
