version: '3'

services:
        db:
                image: postgres
        web:
                build: .
                command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn planner.wsgi -b 0.0.0.0:8080"
                volumes:
                        - ./planner:/code
                expose:
                        - "8080"
                depends_on:
                        - db
        nginx:
                image: nginx
                ports:
                        - "8000:8000"
                volumes:
                        - ./html:/var/www/html
                        - ./config:/etc/nginx/conf.d
                depends_on:
                        - web    

